[package]
name = "simplexp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "simplexp"
crate-type = ["cdylib"]

[dependencies]
konst = "0.2.13"
